  - variance is semantically the opposite index (gap/unenforcement/missing information/randomness) to the filter index (limit/structure/information/organization)
    - includes certainty objects (known variance, metrics, change patterns), uncertainty (potential/risk/opportunity) objects, and variance structures like cascades, injection points, accretion points
    - delegation of variance into systems/types/functions/variables/constants
    - this is the problem of adding/fitting/reducing structure from a gap in structure, which can be used to solve problems like:
      - prediction
        - which variables are explanatory, given what we can measure
      - causation
        - how alternatives can converge to the same level of variance or change patterns
    - reducing gaps in rule enforcement to shapes or paths has its own set of rules
    - this interface can also be used for specific attribute analysis, of properties that descend from concepts & take form in a specific problem space:
      - the power concept interface (has implementations that look like trust, info, etc)
      - the balance concept interface (has implementations that look like symmetry, justice, etc)


'''
  - example of the analysis for this interface: 
    - variance is semantically the opposite index (gap/unenforcement/missing information/randomness) to the filter index (limit/structure/information/organization) 
      - delegation of variance into systems/types/functions/variables/constants/objects 
    - analyzing potential focuses on what errors/functionality/structure is possible/allowed/prevented 

  - functions: 
      - identify high-risk variables 
      - identify imminent variable changes 
      - function to frame change on potential interface: 
        - as change increases, how does potential (possible change) increase: 
          - what probabilities/possibilities become possible (findable/generatable in structural dimensions/on the structural interface) 
          - what possibilities become adjacent/distant 
          - does a change increase or reduce potential options? 
        - as potential changes, how do potential objects/types vary based on the unit of potential (possibility distance, distance between required limits & optional steps) 
      - function to organize position by adjacency determined by probability (more probable changes are more adjacent) 
        - there may be symmetries and limits preventing certain changes from being possible, given a starting point, so each point on the change interface has a set of possible starting points, and traversing the change interface often means a set of points rather than a continuous function, so the set of points needs to be converted to a space where they can be a continuous function to describe time-based change 
      - function to apply/measure change according to time-adjacent variables (potential, change) to increasingly remove the meaning of time structures (like dependence/order/state/prior position), as certain change types make more or all positions possible 
      - function to remove conditions restricting potential (like order, irreversibility, possibility, measurability), eventually leading to the symmetric state where functions producing change would be equivalent to/generative of each other (the theoretical liquid can generate the theoretical cup in that space if it needs to, injecting more time/potential in a prior position on its timeline to further current goals (based on change potential - the set of possible moves given by its current position), which require less change/time/potential than anticipated) 
      - function to maintain potential (alter structure like position/dimension/interface) 
        - dont execute a decision change until needed: allow potential to maintain its superposition (not resolved to a certain structure/path/point) so when you need to, you can choose an aligning path from that potential that fits the post-selection trajectory 
      - function to add potential as needed:  
        - remove traces of resolution into a choice by undoing the root cause up the causal stack (like removing an attribute can restore an object to an undifferentiated type) 
        - add variance-handlers to restore potential lost bc of change cascades that take up time (buy more time by handling current & anticipating imminent change) 
        - remove limits (movement, information, boundaries, rules, structure, attributes) to enable new combinations 
        - acquire power (time, position, information, & other input resources) which is a proxy for potential (range of alternative options) 
        - remove filter determining loss of potential/change by mapping that filter to another one 
        - create efficiencies (shortcuts) to allow existing objects to interact in new ways  
          - change definition of distance so all combinations are possible and adjacent to remove time cost to travel to them 
        - change faster than other changes so other changes could never catch up without your change methods, which youve left information out of so they'd all need to be used together to build your change rate from a different trajectory 
      - function to identify potential structures (conversion potential/interaction space) 

  - attributes: 
    - structure (potential being lack of information, and information being structure) 
  - concepts (randomness, risk/probability, opportunity, certainty, variance, enforcement, validation) 
  - objects: 
    - interaction space 
    - potential field 
  - structures:
    - certainty structures (patterns, rules, constants, assumptions, limits, metrics, information, similarities/matches/alignments (intents/incentives, demand/supply, limit/variation), definitions)
    - uncertainty structures
      - variance structures (gap, leak, cascades/catalysts, accretions/injections, compounding variance, variance building a new interface, variance distribution/alignment, unenforced rules, measurement limits, open systems)
      - potential structures (unused paths/energy/combinations, adjacent states accessible with existing/available resources)
      - change structures (variables, dependencies, updates, replacements, distortions)
    - uncertainty/potential structures: 
      - interaction layer (layer on which objects are likely to interact) 
      - interaction space (set of possible interactions) 
      - potential field (range of potential states or positions) 
      - a chain of risks (uncertainties) is a common structure seen in market patterns (such as trades, product engineering, demand assessment, & prediction markets)
      - asymmetries:
        - info asymmetry (info being better than no info, all other things being equal)
        - understanding asymmetry (understanding being better than a prediction hypothesis)
        - risk chain asymmetry (luck being better than preparation, in edge cases)
      - equivalencies:
        - randomness (in input identity)
        - balance (in resource distribution)
      - variance generators:
        - risk generators (variance-producing variables, such as equal distribution of information, randomizing functions, etc)
        - complex systems (which have greater complexity than that which can be understood by its observers using existing tools) like markets
        - boundary-changing variables/functions
      - variance changers/reducers:
        - risk-reduction structures (using diverse models to check predictions rather than one)
          - categorizing functions (delegating risk to the accuracy of the function combination of variables, constants & operations) 
          - boundaries/limits (minimizing risk & establishing probabilities) 
        - risk-distribution structures (distributing different information to different positions/agents)
          - probability distributions (delegating risk to accuracy of distribution selection) 
        - probabilities (probable convergence/divergence points like filters, constants, etc) 
        - optimization methods

  - answers questions like:
    - what is the conversion potential of this object given its functions
    - what is the interaction space of this object
    - what could this object become in probable system contexts?
    - is this problem solvable in this system context?
'''