'''
  - example of the analysis for this interface: 
    - variance is semantically the opposite index (gap/unenforcement/missing information/randomness) to the filter index (limit/structure/information/organization) 
      - delegation of variance into systems/types/functions/variables/constants/objects 
    - analyzing potential focuses on what errors/functionality/structure is possible/allowed/prevented 
  - functions: 
      - identify high-risk variables 
      - identify imminent variable changes 
      - function to frame change on potential interface: 
        - as change increases, how does potential (possible change) increase: 
          - what probabilities/possibilities become possible (findable/generatable in structural dimensions/on the structural interface) 
          - what possibilities become adjacent/distant 
          - does a change increase or reduce potential options? 
        - as potential changes, how do potential objects/types vary based on the unit of potential (possibility distance, distance between required limits & optional steps) 
      - function to organize position by adjacency determined by probability (more probable changes are more adjacent) 
        - there may be symmetries and limits preventing certain changes from being possible, given a starting point, so each point on the change interface has a set of possible starting points, and traversing the change interface often means a set of points rather than a continuous function, so the set of points needs to be converted to a space where they can be a continuous function to describe time-based change 
      - function to apply/measure change according to time-adjacent variables (potential, change) to increasingly remove the meaning of time structures (like dependence/order/state/prior position), as certain change types make more or all positions possible 
      - function to remove conditions restricting potential (like order, irreversibility, possibility, measurability), eventually leading to the symmetric state where functions producing change would be equivalent to/generative of each other (the theoretical liquid can generate the theoretical cup in that space if it needs to, injecting more time/potential in a prior position on its timeline to further current goals (based on change potential - the set of possible moves given by its current position), which require less change/time/potential than anticipated) 
      - function to maintain potential (alter structure like position/dimension/interface) 
        - dont execute a decision change until needed: allow potential to maintain its superposition (not resolved to a certain structure/path/point) so when you need to, you can choose an aligning path from that potential that fits the post-selection trajectory 
      - function to add potential as needed:  
        - remove traces of resolution into a choice by undoing the root cause up the causal stack (like removing an attribute can restore an object to an undifferentiated type) 
        - add variance-handlers to restore potential lost bc of change cascades that take up time (buy more time by handling current & anticipating imminent change) 
        - remove limits (movement, information, boundaries, rules, structure, attributes) to enable new combinations 
        - acquire power (time, position, information, & other input resources) which is a proxy for potential (range of alternative options) 
        - remove filter determining loss of potential/change by mapping that filter to another one 
        - create efficiencies (shortcuts) to allow existing objects to interact in new ways  
          - change definition of distance so all combinations are possible and adjacent to remove time cost to travel to them 
        - change faster than other changes so other changes could never catch up without your change methods, which youve left information out of so they'd all need to be used together to build your change rate from a different trajectory 
      - function to identify potential structures (conversion potential/interaction space) 

  - attributes: 
    - structure (potential being lack of information, and information being structure) 
  - concepts (randomness, risk/probability, opportunity, certainty, variance, enforcement, validation) 
  - objects: 
    - interaction space 
    - potential field 
  - structures:
    - certainty structures (patterns, rules, constants, assumptions, limits, metrics, information, similarities/matches/alignments (intents/incentives, demand/supply, limit/variation), definitions)
    - uncertainty structures
      - variance structures (gap, leak, cascades/catalysts, accretions/injections, compounding variance, variance building a new interface, variance distribution/alignment, unenforced rules, measurement limits, open systems)
      - potential structures (unused paths/energy/combinations, adjacent states accessible with existing/available resources)
      - change structures (variables, dependencies, updates, replacements, distortions)
    - uncertainty/potential structures: 
        - unused resources (paths/energy/combinations) 
        - adjacent states accessible with existing/available resources 
        - complex systems (which have greater complexity than that which can be understood by its observers using existing tools) like markets 
        - risk generators (variance-producing variables, such as equal distribution of information, randomizing functions, etc) 
        - boundary/limit-changing functions 
        - risk structures: a chain of risks (uncertainties) is a common structure seen in market patterns (such as trades, product engineering, demand assessment, & prediction markets) 
        - risk-reduction structures (using diverse models to check predictions rather than one) 
            - categorizing functions (delegating risk to the accuracy of the function combination of variables, constants & operations) 
            - boundaries/limits (minimizing risk & establishing probabilities) 
        - risk-distribution structures (distributing different information to different positions/agents) 
          - probability distributions (delegating risk to accuracy of distribution selection) 
        - probabilities (probable convergence/divergence points like filters, constants, etc) 
      - interaction layer (layer on which objects are likely to interact) 
      - interaction space (set of possible interactions) 
      - potential field (range of potential states or positions) 

  - answers questions like:
    - what is the conversion potential of this object given its functions
    - what is the interaction space of this object
    - predict which system filters will be useful based on a system priority
    - this is the problem of adding/fitting/reducing structure from a gap in structure, which can be used to solve problems like:
      - prediction
        - which variables are explanatory, given what we can measure
      - causation
        - how alternatives can converge to the same level of variance or change patterns
    - reducing gaps in rule enforcement to shapes/paths has its own set of rules
    - this interface can also be used for specific attribute analysis, of properties that descend from concepts & take form in a specific problem space:
      - the power concept interface (has structures that look like trust, info, etc)
      - the balance concept interface (has structures that look like symmetry, justice, etc)
    - what type of variable is it? (object-differentiating/identifying attribute, emergent specific/abstract property, direct function input/output)
      - how does the variable relate to other variables? (decisive metric, substitutable alternative, collinear)
      - at what point does a variable become relevant to another variable interaction layer?
      - how do constants accrete between rules, like caps to keep variance from flowing in to corners or creating boundary-invalidating openings in a system/component boundary?
      - what causes variables to cascade across layers, creating fractal variables?
      - what is the path definitely not, based on various maximized measures of similarity?
      - what attributes & attribute sets & attribute dependency trees differ
      - what is transformation cost/potential between objects
      - what is divergence distance between generative paths for each object
      - what is the probable function linking these variables, given that it is an adjacent transform of a square (related function type), & a distant transform of a manifold (unrelated function type)?
    - how does a system become overwhelmed with variance (in various forms, including randomness), does it have outlets like interfaces with other systems to delegate variance

'''