[
'__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', 
'__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_next', 
'addAtom', 'addBond', 'addCatalyst', 'addConstraint', 'addConstraintNot', 'addConstraintOr', 'addDataSGroup', 'addDecomposition', 'addProduct', 'addRSite', 'addReactant', 'addSGroupAttachmentPoint', 
'addStereocenter', 'addSuperatom', 'addTemplate', 'alignAtoms', 'allScaffolds', 'append', 'aromatize', 'arrayAdd', 'at', 'atomMappingNumber', 'atomicNumber', 'automap', 'bond', 'bondOrder', 'bondStereo', 
'canonicalSmarts', 'canonicalSmiles', 'cdxml', 'changeStereocenterType', 'charge', 
'check', 'check3DStereo', 'checkAmbiguousH', 'checkBadValence', 'checkChirality', 'checkQuery', 'checkRGroups', 'checkStereo', 'checkValence', 
'clean2d', 'clear', 'clearAAM', 'clearAlleneCenters', 'clearAttachmentPoints', 'clearCisTrans', 'clearProperties', 'clearStereocenters', 'clone', 'close', 'cml', 'cmlAppend', 'cmlFooter', 
'cmlHeader', 
'component', 'componentIndex', 'correctReactingCenters', 
'count', 'countAlleneCenters', 'countAtoms', 'countAttachmentPoints', 'countBits', 'countBonds', 'countCatalysts', 'countComponents', 
'countDataSGroups', 'countGenericSGroups', 'countHeavyAtoms', 'countHydrogens', 'countImplicitHydrogens', 'countMatches', 'countMatchesWithLimit', 'countMolecules', 'countMultipleGroups', 'countProducts', 
'countPseudoatoms', 'countRGroups', 'countRSites', 'countReactants', 'countRepeatingUnits', 'countSSSR', 'countStereocenters', 'countSuperatoms', 
'createEdgeSubmolecule', 'createSGroup', 'createSubmolecule', 
'data', 'dbgInternalType', 'dearomatize', 'decomposeMolecule', 'decomposedMoleculeHighlighted', 'decomposedMoleculeScaffold', 'decomposedMoleculeWithRGroups', 'degree', 'deleteSGroupAttachmentPoint', 
'description', 'destination', 'dispatcher', 'dispose', 'expandAbbreviations', 'findSGroups', 'findTemplate', 'fingerprint', 'foldHydrogens', 
'getAcidPkaValue', 'getAtom', 'getBasicPkaValue', 'getBond', 'getDataSGroup', 'getExplicitValence', 'getGenericSGroup', 'getMolecule', 'getMultipleGroup', 'getProperty', 'getRepeatingUnit', 'getRepeatingUnitConnectivity', 'getRepeatingUnitSubscript', 'getSGroupClass', 
'getSGroupCoords', 'getSGroupDisplayOption', 'getSGroupIndex', 'getSGroupMultiplier', 'getSGroupName', 'getSGroupNumCrossBonds', 'getSGroupOriginalId', 'getSGroupParentId', 'getSGroupSeqId', 'getSGroupType', 
'getSubmolecule', 'getSuperatom', 'getTGroupAlias', 'getTGroupClass', 'getTGroupName', 'getTemplateAtomClass', 
'grossFormula', 
'hasCoord', 'hasNext', 'hasProperty', 'hasZCoord', 
'highlight', 'highlightedTarget', 
'id', 'ignoreAtom', 'index', 'invertStereo', 'ionize', 
'isChiral', 'isHighlighted', 'isPossibleFischerProjection', 'isPseudoatom', 'isRSite', 'isTemplateAtom', 
'isotope', 
'iterateAlleneCenters', 'iterateArray', 'iterateAtoms', 'iterateAttachmentPoints', 'iterateBonds', 'iterateCatalysts', 'iterateComponents', 'iterateDataSGroups', 'iterateDecomposedMolecules', 'iterateDecompositions', 'iterateEdgeSubmolecules', 
'iterateGenericSGroups', 'iterateMatches', 'iterateMolecules', 'iterateMultipleGroups', 'iterateNeighbors', 'iterateProducts', 'iterateProperties', 'iteratePseudoatoms', 'iterateRGroupFragments', 'iterateRGroups', 
'iterateRSites', 'iterateReactants', 'iterateRepeatingUnits', 'iterateRings', 'iterateSGroups', 'iterateSSSR', 'iterateStereocenters', 'iterateSubtrees', 'iterateSuperatoms', 'iterateTGroups', 
'json', 'layeredCode', 'layout', 
'mapAtom', 'mapBond', 'mapMolecule', 
'markEitherCisTrans', 'markStereobonds', 
'massComposition', 'match', 'mdlct', 'merge', 'molecularWeight', 'molfile', 'monoisotopicMass', 'mostAbundantMass', 'name', 'next', 'normalize', 'oneBitsList', 'optimize', 'parent', 
'radical', 'radicalElectrons', 'rawData', 'rdfAppend', 'rdfHeader', 'reactingCenter', 
'remove', 'removeAtoms', 'removeBonds', 'removeConstraints', 'removeProperty', 'removeTemplate', 
'resetAtom', 'resetCharge', 'resetExplicitValence', 'resetIsotope', 'resetRadical', 'resetStereo', 'resetSymmetricCisTrans', 'resetSymmetricStereocenters', 
'rxnfile', 'saveCdxml', 'saveCml', 'saveMDLCT', 'saveMolfile', 'saveRxnfile', 'sdfAppend', 'serialize', 
'setAtomMappingNumber', 'setAttachmentPoint', 'setBondOrder', 'setCharge', 'setDataSGroupXY', 'setExplicitValence', 'setImplicitHCount', 'setIsotope', 'setName', 'setProperty', 'setRSite', 'setRadical', 
'setReactingCenter', 'setSGroupBrackets', 'setSGroupClass', 'setSGroupCoords', 'setSGroupData', 'setSGroupDataType', 'setSGroupDescription', 'setSGroupDisplay', 'setSGroupDisplayOption', 'setSGroupFieldName', 
'setSGroupLocation', 'setSGroupMultiplier', 'setSGroupName', 'setSGroupOriginalId', 'setSGroupParentId', 'setSGroupQueryCode', 'setSGroupQueryOper', 'setSGroupTag', 'setSGroupTagAlign', 'setSGroupXCoord', 
'setSGroupYCoord', 'setStereocenterGroup', 'setTemplateAtomClass', 'setXYZ', 
'singleAllowedRGroup', 'smarts', 'smiles', 'smilesAppend', 'source', 'standardize', 
'stereocenterGroup', 'stereocenterPyramid', 'stereocenterType', 'symbol', 'symmetryClasses', 'tell', 'toBuffer', 'toString', 
'topology', 'transformCTABtoSCSR', 'transformSCSRtoCTAB', 
'unfoldHydrogens', 'unhighlight', 'unignoreAllAtoms', 'unignoreAtom', 
'valence', 'validateChirality', 'xyz'
]
