'''
- function to find/derive/build an interim interface to standardize components from multiple interfaces 
      - example: changes from other interfaces can all be framed on the interim change interface 

- function to determine adjacent/causative/generative/descriptive/alternative interfaces 

- finding the structure of cross-interface interactions, such as: 
      - finding patterns in ratios between uncertainty generated by a function combination vs. uncertainty-reduction function patterns & potential  
      - determining the relationship between the function converting one structure into another & the function converting its determining/descriptive/causative/generative variables 
      - finding valid/invalid change types in a structure 
      - finding structures fulfilling a concept combination & trajectory to the objects in that structure whose differences are relevant to those concepts 
      - determining the impact of operations done on one attribute (length) vs. another attribute (angle) 
      - finding how core operations & objects develop & accrete in a structure (like a system) 
      - deriving object types with attributes useful for a particular operation ("quaternions for 3-d rotation") 
      - converting information objects (like value) into system objects (like units, such as integer units) 
      - finding patterns that turn into objects that attract/hold the most variance 
      - how to generate a new solution automation workflow 
      - what solution automation workflow is optimal for this problem 

'''