'''

    - function to derive core components of the program from other core components

        - derive the interface network from an interface 
          - each interface network in the set of interfaces (core function interface network, general interface network, specific interface network) can be used to generate the others 
            - intent interface can be used to generate the type interface 
            - dependency interface can be used to generate the side effect interface 
            - interface network can be used to generate the core function interface 
        
        - generating full set of general interfaces (intent, concept, structure) 
          - these can be generated by identifying the key differentiating factors across systems, which can be generated as combinations of objects  
            - type is a combination of attributes 
            - intent is a combination of function effects 
            - concept is a network of networks describing a structural concept (balance, power) 
            - structure is a combination of information & rules  


'''